apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.projectName }}
  description: Cluster EKS com pipeline OpenTofu provisionado via Backstage
  tags:
    - eks
    - terraform
    - opentofu
    - kubernetes
    - aws
  annotations:
    github.com/project-slug: ${{ values.owner }}/${{ values.projectName }}
spec:
  type: service
  lifecycle: experimental
  owner: platform-team
