stages:
  - deploy

deploy:
  stage: deploy
  script:
    - echo "Fazendo deploy do CloudFormation"
    - aws cloudformation deploy \
        --template-file cloudformation/s3-cloudfront.yaml \
        --stack-name "${{ repoName | dump}}-cloudfront-stack" \
        --capabilities CAPABILITY_NAMED_IAM