apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: gitops-cluster-repo
  title: Repositório GitOps (AWS ALB + Ingress-nginx)
  description: Cria um repositório GitOps com estrutura padrão de gerenciamento kubernetes
  tags:
    - gitops
    - argocd
    - kubernetes
    - aws
spec:
  owner: gitops-plataform
  type: gitops

  parameters:
    - title: Informações do Repositório
      required: [projectName, owner]
      properties:
        projectName:
          title: Nome do Repositório
          type: string
          default: cluster-management
        owner:
          title: Organização ou Usuário GitHub
          type: string
          default: pcnuness

  steps:
    - id: step-base
      name: Gerar Estrutura GitOps Completa
      action: fetch:template
      input:
        url: ./gitops-cluster-repo/templates/cluster-management
        targetPath: .
        values:
          projectName: ${{ parameters.projectName }}
          owner: ${{ parameters.owner }}

    - id: step-push
      name: Commit Inicial no GitHub
      action: publish:github
      input:
        repoUrl: "github.com?owner=${{ parameters.owner }}&repo=${{ parameters.projectName }}"
        branch: main
        defaultBranch: main
        commitMessage: "Initial commit com estrutura GitOps completa"
        authorName: Backstage Scaffolder
        authorEmail: scaffolder@domain.com
        committerName: Backstage Scaffolder
        committerEmail: scaffolder@domain.com

  output:
    links:
      - title: Repositório GitHub
        url: "https://github.com/${{ parameters.owner }}/${{ parameters.projectName }}"