apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: gitops-cluster-repo
  title: Novo Repositório GitOps de Gerenciamento de Cluster
  description: Cria um novo repositório GitOps com a estrutura padrão para gerenciamento de cluster por cliente, aplicação ou produto.
  tags:
    - gitops
    - argocd
    - kubernetes
    - backstage
    - aws
    - github
spec:
  owner: gitops-plataform
  type: gitops
  parameters:
    - title: GitOps Repository Details
      required: [projectName, owner]
      properties:
        projectName:
          title: Nome do Repositório GitOps
          type: string
          default: cluster-management
        owner:
          title: Organização ou Usuário no GitHub
          type: string
          default: pcnunes
    - title: Configuração de Addons
      properties:
        addonsAWS:
          title: Selecione Add-ons AWS
          type: array
          items:
            type: string
            enum:
              - load-balancer-controller
              - external-dns
              - ebs-csi-driver
          default: ["load-balancer-controller"]
        addonsOSS:
          title: Selecione Add-ons OSS
          type: array
          items:
            type: string
            enum:
              - crossplane
              - ingress-nginx
              - argocd-ingress
          default: ["crossplane"]
  steps:
    - id: fetch-template
      name: Gerar estrutura GitOps com Addons
      action: fetch:template
      input:
        targetPath: "."
        url: "./templates"
        values:
          projectName: ${{ parameters.projectName }}
          owner: ${{ parameters.owner }}
          AddonsAWS: ${{ parameters.AddonsAWS }}
          AddonsOSS: ${{ parameters.AddonsOSS }}

    - id: push-initial
      name: Push Inicial
      action: publish:github
      input:
        repoUrl: "github.com?owner=${{ parameters.owner }}&repo=${{ parameters.projectName }}"
        branch: main
        defaultBranch: main
        committerName: "Backstage Scaffolder"
        committerEmail: "scaffolder@mydomain.com"
        authorName: "Backstage Scaffolder"
        authorEmail: "scaffolder@mydomain.com"
        commitMessage: "Initial commit from Scaffolder"
        files:
          - source: "."
            target: "/"

    # - id: create_pr
    #   name: Criar Pull Request
    #   action: publish:github:pull-request
    #   input:
    #     repoUrl: "github.com?owner=${{ parameters.owner }}&repo=${{ parameters.projectName }}"
    #     title: "feat: ${{ parameters.projectName }} - estrutura GitOps base"
    #     branchName: "feat-${{ parameters.projectName }}"
    #     description: "Código para provisionar estrutura GitOps com os add-ons ${{ parameters.AddonsAWS }} e ${{ parameters.AddonsOSS }}"
    #     sourcePath: "."
    #     targetPath: "./"

  output:
    links:
      - title: Projeto GitHub
        url: "${{ steps.create_pr.output.remoteUrl }}"
        text: "Pull Request criado"
