apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: gitops-cluster-default
  title: Repositório GitOps
  description: Cria repositório GitOps com estrutura default de gerenciamento (AWS ALB Controller and Ingress-Nginx)
  tags:
    - gitops
    - argocd
    - kubernetes
    - aws
spec:
  owner: gitops-plataform
  type: gitops

  parameters:
    - title: Informações do Repositório
      required: [projectName, owner]
      properties:
        projectName:
          title: Nome do Repositório
          type: string
          default: gitops-cluster
        owner:
          title: Organização ou Usuário GitHub
          type: string
          default: pcnuness
          
  steps:
    - id: fetch-template
      name: Gerar estrutura GitOps com Addons
      action: fetch:template
      input:
        targetPath: "."
        url: "./templates"
        values:
          projectName: ${{ parameters.projectName }}
          owner: ${{ parameters.owner }}
          AddonsAWS: ${{ parameters.AddonsAWS }}
          AddonsOSS: ${{ parameters.AddonsOSS }}

    - id: push-initial
      name: Push Inicial
      action: publish:github
      input:
        repoUrl: "github.com?owner=${{ parameters.owner }}&repo=${{ parameters.projectName }}"
        branch: main
        defaultBranch: main
        committerName: "Backstage Scaffolder"
        committerEmail: "scaffolder@mydomain.com"
        authorName: "Backstage Scaffolder"
        authorEmail: "scaffolder@mydomain.com"
        commitMessage: "Initial commit from Scaffolder"
        files:
          - source: "."
            target: "/"

  output:
    links:
      - title: Repositório GitHub
        url: "https://github.com/${{ parameters.owner }}/${{ parameters.projectName }}"