apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: gitops-cluster-repo
  title: Novo Repositório GitOps com Addons
  description: Cria um repositório GitOps com estrutura padrão de gerenciamento de cluster e opções de addons AWS e OSS.
  tags:
    - gitops
    - argocd
    - kubernetes
    - aws
    - addons
spec:
  owner: gitops-plataform
  type: gitops
  parameters:
    - title: Informações do Repositório
      required: [projectName, owner]
      properties:
        projectName:
          title: Nome do Repositório
          type: string
          default: cluster-management
        owner:
          title: Organização ou Usuário GitHub
          type: string
          default: pcnunes

    - title: Seleção de Addons
      properties:
        addonsAWS:
          title: Add-ons AWS
          type: array
          items:
            type: string
            enum:
              - load-balancer-controller
          default: ["load-balancer-controller"]
        addonsOSS:
          title: Add-ons OSS
          type: array
          items:
            type: string
            enum:
              - crossplane
          default: ["crossplane"]

  steps:
    - id: step-base
      name: Gerar Estrutura Base
      action: fetch:template
      input:
        url: ./base
        targetPath: .
        values:
          projectName: ${{ parameters.projectName }}
          owner: ${{ parameters.owner }}

    # Loop pelos Addons AWS selecionados
    - id: step-aws
      name: Gerar Addons AWS
      if: ${{ parameters.addonsAWS && parameters.addonsAWS.length > 0 }}
      action: fetch:template
      input:
        url: ./addons/aws
        targetPath: .
        values:
          selectedAddons: ${{ parameters.addonsAWS }}

    # Loop pelos Addons OSS selecionados
    - id: step-oss
      name: Gerar Addons OSS
      if: ${{ parameters.addonsOSS && parameters.addonsOSS.length > 0 }}
      action: fetch:template
      input:
        url: ./addons/oss
        targetPath: .
        values:
          selectedAddons: ${{ parameters.addonsOSS }}

    - id: step-push
      name: Push Inicial
      action: publish:github
      input:
        repoUrl: "github.com?owner=${{ parameters.owner }}&repo=${{ parameters.projectName }}"
        branch: main
        defaultBranch: main
        commitMessage: "Initial commit com estrutura GitOps e addons selecionados"
        authorName: Backstage Scaffolder
        authorEmail: scaffolder@domain.com
        committerName: Backstage Scaffolder
        committerEmail: scaffolder@domain.com

  output:
    links:
      - title: Repositório GitHub
        url: "https://github.com/${{ parameters.owner }}/${{ parameters.projectName }}"