apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: cloudfront-s3
  title: "Provisionamento de CloudFront com S3"
  description: "Template para provisionar um bucket S3 e distribuição CloudFront na AWS via CloudFormation"
  tags:
    - aws
    - cloudformation
    - s3
    - cloudfront
spec:
  owner: "engineering"
  type: service