apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: opentofu-eks-autopilot-8
  title: OpenTofu EKS Cluster com Pipeline Autopilot -8
  description: |
    Template para criação de clusters EKS usando OpenTofu com pipeline autopilot.
    Suporta múltiplos ambientes (dev, stage, prod) com tfvars específicos.
  tags:
    - opentofu
    - terraform
    - eks
    - kubernetes
    - aws
    - gitops
    - argocd
    - infrastructure
    - autopilot
  links:
    - url: https://opentofu.org/docs/
      title: OpenTofu Documentation
      icon: docs
    - url: https://aws.amazon.com/eks/
      title: Amazon EKS
      icon: cloud

spec:
  owner: platform-team
  type: infrastructure
  
  parameters:
    # ===== CONFIGURAÇÕES PRINCIPAIS =====
    - title: 🏗️ Configurações Principais
      required:
        - projectName
        - owner
        - awsRegion
        - environments
      properties:
        projectName:
          title: Nome do Repositório
          type: string
          description: Nome do repositório a ser criado
          default: meu-cluster-gitops
          pattern: '^[a-zA-Z0-9-_]+$'
        owner:
          title: Organização ou Usuário GitHub
          type: string
          description: Organização ou usuário GitHub que será proprietário do repositório
          default: pcnuness
          pattern: '^[a-zA-Z0-9-_]+$'

        awsRegion:
          title: Região AWS
          type: string
          description: Região AWS para deploy da infraestrutura
          default: us-east-1
          enum:
            - us-east-1
            - us-west-2
            - eu-west-1
            - eu-central-1
            - ap-southeast-1
          enumNames:
            - 'US East (N. Virginia)'
            - 'US West (Oregon)'
            - 'Europe (Ireland)'
            - 'Europe (Frankfurt)'
            - 'Asia Pacific (Singapore)'

        environments:
          title: Selecione os ambientes que serão configurados
          properties:
            enabledDev:
              title: Ambiente Develop
              type: boolean
              description: Habilitar Develop
              default: true
            enabledStage:
              title: Ambiente Stage
              type: boolean
              description: Habilitar Stage
              default: false
            enabledProd:
              title: Ambiente Production
              type: boolean
              description: Habilitar Production
              default: false

    # ===== CONFIGURAÇÕES DO CLUSTER EKS =====
    - title: ⚙️ Configurações do Cluster EKS
      required:
        - clusterVersion
      properties:
        clusterVersion:
          title: Versão do Kubernetes
          type: string
          description: Versão do Kubernetes para o cluster EKS
          default: "1.31"
          enum:
            - "1.29"
            - "1.30"
            - "1.31"
            - "1.32"

    # ===== ADDONS E COMPONENTES =====
    - title: 🔧 Addons e Componentes
      properties:
        enabledCoreDns:
          title: Addon Core DNS
          type: boolean
          description: Habilitar Core DNS
          default: true
        enabledKubeProxy:
          title: Addon Kube Proxy
          type: boolean
          description: Habilitar Kube Proxy
          default: false
        enabledPodIdentityAgent:
          title: Addon AWS Pod Identity Agent
          type: boolean
          description: Habilitar Pod Identity Agent
          default: false
        enabledEbsCsiDriver:
          title: Addon AWS EBS CSI Driver
          type: boolean
          description: Habilitar WS EBS CSI Driver
          default: false

    # ===== CONFIGURAÇÕES DE GOVERNANÇA =====
    - title: 📋 Configurações de Governança
      properties:
        priority:
          title: Prioridade da Solicitação
          type: string
          description: Prioridade para aprovação e processamento
          default: medium
          enum:
            - low
            - medium
            - high
            - critical
          enumNames:
            - 'Baixa - Desenvolvimento/Teste'
            - 'Média - Staging/QA'
            - 'Alta - Produção'
            - 'Crítica - Emergência'

        reviewers:
          title: Revisores Adicionais
          type: array
          description: Usuários GitHub para revisar o PR (além dos padrão)
          items:
            type: string
          ui:help: 'Usernames do GitHub, um por linha'

        createDraft:
          title: Criar como Draft
          type: boolean
          description: Criar PR como draft para revisão antes da aprovação
          default: false

  steps:
    # ===== VALIDAÇÃO INICIAL =====
    - id: validate-inputs
      name: 🔍 Validar Entradas
      action: debug:log
      input:
        message: |
          Validando configurações:
          - Projeto: ${{ parameters.projectName }}
          - Owner: ${{ parameters.owner }}
          - Região: ${{ parameters.awsRegion }}
          - Cluster Version: ${{ parameters.clusterVersion }}
          - Ambientes:
              ${{ parameters.enabledProd}}
              ${{ parameters.enabledStage }}
              ${{ parameters.enabledDev }}
          - Addons: 
              ${{ parameters.enabledCoreDns }}
              ${{ parameters.enabledKubeProxy }} 
              {{ parameters.enabledPodIdentityAgent }}
              ${{ parameters.enabledEbsCsiDriver }}
        values:
          projectName: ${{ parameters.projectName }}
          owner: ${{ parameters.owner }}
          awsRegion: ${{ parameters.awsRegion }}
          clusterVersion: ${{ parameters.clusterVersion }}
          enabledProd: ${{ parameters.enabledProd }}
          enabledProd: ${{ parameters.enabledStage }}
          enabledProd: ${{ parameters.enabledDev }}
          enabledCoreDns: ${{ parameters.enabledCoreDns }}
          enabledKubeProxy: ${{ parameters.enabledKubeProxy }}
          enabledPodIdentityAgent: ${{ parameters.enabledPodIdentityAgent }}
          enabledEbsCsiDriver: ${{ parameters.enabledEbsCsiDriver }}

    # ===== FETCH ARQUIVOS ESTÁTICOS =====
    - id: fetch-base-structure
      name: 📁 Buscar Estrutura Base
      action: fetch:template
      input:
        url: ./templates/terraform/
        targetPath: ./terraform
        values:
          projectName: ${{ parameters.projectName }}
          owner: ${{ parameters.owner }}
          awsRegion: ${{ parameters.awsRegion }}
          clusterVersion: ${{ parameters.clusterVersion }}
          environments: ${{ parameters.environments }}
          enabledCoreDns: ${{ parameters.enabledCoreDns }}
          enabledKubeProxy: ${{ parameters.enabledKubeProxy }}
          enabledPodIdentityAgent: ${{ parameters.enabledPodIdentityAgent }}
          enabledEbsCsiDriver: ${{ parameters.enabledEbsCsiDriver }}

    # ===== CRIAR REPOSITÓRIO =====
    - id: publish-repo
      name: 📦 Criar Repositório
      action: publish:github
      input:
        repoUrl: github.com?owner=${{ parameters.owner }}&repo=${{ parameters.projectName }}
        description: 'Infraestrutura EKS para ${{ parameters.projectName }} usando OpenTofu'
        homepage: https://github.com/${{ values.owner }}/${{ values.projectName }}
        topics:
          - opentofu
          - terraform
          - eks
          - kubernetes
          - aws
          - infrastructure
          - ${{ parameters.projectName }}
        defaultBranch: main
        gitAuthorName: Backstage Scaffolder
        gitAuthorEmail: scaffolder@backstage.io
        repoVisibility: public
        gitCommitMessage: |
          🚀 Initial commit: OpenTofu EKS Infrastructure for ${{ parameters.projectName }}

          - Configuração completa de cluster EKS
          - Pipeline autopilot com GitHub Actions
          - Suporte a múltiplos ambientes: ${{ parameters.environments | join(', ') }}
          - Região: ${{ parameters.awsRegion }}
          - Kubernetes: v${{ parameters.clusterVersion }}
          
          Criado via Backstage Scaffolder

    # ===== AGUARDAR PROPAGAÇÃO =====
    - id: wait-for-repo
      name: ⏳ Aguardar Propagação do Repositório
      action: debug:log
      input:
        message: |
          ⏳ Aguardando propagação do repositório no GitHub...
          Repositório: https://github.com/${{ values.owner }}/${{ values.projectName }}.git
          
          Aguardando 10 segundos para garantir que os arquivos estejam disponíveis via API...

    # ===== REGISTRAR NO CATÁLOGO (COM RETRY) =====
    - id: register-catalog
      name: 📋 Registrar no Catálogo
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish-repo'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'
        optional: true

  output:
    links:
      - title: 📦 Ver Repositório
        url: https://github.com/${{ values.owner }}/${{ values.projectName }}
        icon: github

      - title: 📊 Pipeline Status
        url: https://github.com/${{ values.owner }}/${{ values.projectName }}/actions
        icon: github

      - title: 📋 Registrar Manualmente no Catálogo
        url: /catalog-import
        icon: catalog

      - title: 📖 OpenTofu Documentation
        url: https://opentofu.org/docs/
        icon: docs

      - title: ☁️ AWS EKS Console
        url: https://console.aws.amazon.com/eks/home?region=${{ parameters.awsRegion }}#/clusters
        icon: cloud

    text:
      - title: 🎉 Infraestrutura OpenTofu Criada com Sucesso!
        content: |
          ## ✅ Repositório Criado:
          
          **Repositório:** https://github.com/${{ values.owner }}/${{ values.projectName }}/actions
          
          ## 📋 Registro no Catálogo:
          
          Se o registro automático falhou, você pode registrar manualmente:
          
          1. **Acesse:** [Catalog Import](/catalog-import)
          2. **Cole a URL:** `https://github.com/${{ values.owner }}/${{ values.projectName }}/actions/blob/main/catalog-info.yaml`
          3. **Clique em:** "Analyze"
          4. **Confirme:** "Import"
          
          ## 🚀 Próximos Passos:
          
          ### 1. 📦 Verificar Repositório
          - Acesse o repositório criado no GitHub
          - Verifique se todos os arquivos estão corretos
          
          ### 2. 🚀 Executar Pipeline
          - Vá para a aba Actions do repositório
          - Execute a pipeline manualmente para o ambiente desejado:
            ```bash
            # Exemplo para ambiente dev
            gh workflow run "Deploy OpenTofu EKS" --field stage=dev --field action=plan
            ```
          
          ### 3. 🔧 Configurações Pós-Deploy
          - Configure kubectl: `aws eks update-kubeconfig --region ${{ parameters.awsRegion }} --name ${{ parameters.projectName }}-eks`
          - Valide conectividade com o cluster
          - Configure aplicações no ArgoCD (se habilitado)
          
          ## 📊 Resumo da Configuração:
          - **Projeto:** ${{ parameters.projectName }}
          - **Ambientes:** ${{ parameters.environments | join(', ') }}
          - **Região:** ${{ parameters.awsRegion }}
          - **Kubernetes:** v${{ parameters.clusterVersion }}
          ## 🆘 Suporte:
          Em caso de dúvidas ou problemas, consulte a documentação ou entre em contato com a equipe de platform.