apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: opentofu-eks-autopilot
  title: OpenTofu EKS Cluster com Pipeline Autopilot
  description: |
    Template para criação de clusters EKS usando OpenTofu com pipeline autopilot.
    Inclui configuração completa de infraestrutura, addons e GitOps com ArgoCD.
    Suporta múltiplos ambientes (dev, stage, prod) com tfvars específicos.
  tags:
    - opentofu
    - terraform
    - eks
    - kubernetes
    - aws
    - gitops
    - argocd
    - infrastructure
    - autopilot
  links:
    - url: https://opentofu.org/docs/
      title: OpenTofu Documentation
      icon: docs
    - url: https://aws.amazon.com/eks/
      title: Amazon EKS
      icon: cloud

spec:
  owner: platform-team
  type: infrastructure
  
  parameters:
    # ===== CONFIGURAÇÕES PRINCIPAIS =====
    - title: 🏗️ Configurações Principais
      required:
        - projectName
        - repoUrl
        - awsRegion
        - environments
      properties:
        projectName:
          title: Nome do Projeto
          type: string
          description: Nome do projeto (usado para prefixos de recursos)
          pattern: '^[a-z][a-z0-9-]*[a-z0-9]$'
          maxLength: 20
          ui:autofocus: true
          ui:help: 'Apenas letras minúsculas, números e hífens. Deve começar com letra.'

        repoUrl:
          title: Repositório de Destino
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
          description: Repositório onde o código será criado

        awsRegion:
          title: Região AWS
          type: string
          description: Região AWS para deploy da infraestrutura
          default: us-east-1
          enum:
            - us-east-1
            - us-west-2
            - eu-west-1
            - eu-central-1
            - ap-southeast-1
          enumNames:
            - 'US East (N. Virginia)'
            - 'US West (Oregon)'
            - 'Europe (Ireland)'
            - 'Europe (Frankfurt)'
            - 'Asia Pacific (Singapore)'

        environments:
          title: Ambientes a Configurar
          type: array
          description: Selecione os ambientes que serão configurados
          uniqueItems: true
          ui:widget: checkboxes
          items:
            type: string
            enum:
              - dev
              - stage
              - prod
          default:
            - dev

    # ===== CONFIGURAÇÕES DO CLUSTER EKS =====
    - title: ⚙️ Configurações do Cluster EKS
      properties:
        clusterVersion:
          title: Versão do Kubernetes
          type: string
          description: Versão do Kubernetes para o cluster EKS
          default: "1.28"
          enum:
            - "1.26"
            - "1.27"
            - "1.28"
            - "1.29"

    # ===== ADDONS E COMPONENTES =====
    - title: 🔧 Addons e Componentes
      properties:
        enabledAddons:
          title: Addons Habilitados
          type: array
          description: Selecione os addons que serão instalados no cluster
          uniqueItems: true
          ui:widget: checkboxes
          items:
            type: string
            enum:
              - aws-ebs-csi-driver
              - coredns
              - kube-proxy
              - eks-pod-identity-agent
              - adot
              - argocd
          enumNames:
            - AWS EBS CSI Driver
            - CoreDNS
            - Kube Proxy
            - EKS Pod Identity Agent
            - AWS Distro for OpenTelemetry
            - ArgoCD
          default:
            - aws-ebs-csi-driver
            - coredns
            - kube-proxy

    # ===== CONFIGURAÇÕES DE GOVERNANÇA =====
    - title: 📋 Configurações de Governança
      properties:
        priority:
          title: Prioridade da Solicitação
          type: string
          description: Prioridade para aprovação e processamento
          default: medium
          enum:
            - low
            - medium
            - high
            - critical
          enumNames:
            - 'Baixa - Desenvolvimento/Teste'
            - 'Média - Staging/QA'
            - 'Alta - Produção'
            - 'Crítica - Emergência'

        reviewers:
          title: Revisores Adicionais
          type: array
          description: Usuários GitHub para revisar o PR (além dos padrão)
          items:
            type: string
          ui:help: 'Usernames do GitHub, um por linha'

        createDraft:
          title: Criar como Draft
          type: boolean
          description: Criar PR como draft para revisão antes da aprovação
          default: false

  steps:
    # ===== VALIDAÇÃO INICIAL =====
    - id: validate-inputs
      name: 🔍 Validar Entradas
      action: debug:log
      input:
        message: |
          Validando configurações:
          - Projeto: ${{ parameters.projectName }}
          - Região: ${{ parameters.awsRegion }}
          - Ambientes: ${{ parameters.environments | join(', ') }}
          - Cluster Version: ${{ parameters.clusterVersion }}

    # ===== FETCH ARQUIVOS ESTÁTICOS =====
    - id: fetch-static
      name: 📥 Buscar Arquivos Base
      action: fetch:plain
      input:
        url: ./skeleton
        targetPath: .

    # ===== PROCESSAR TEMPLATES DINÂMICOS =====
    - id: process-tfvars
      name: 🛠️ Processar Arquivos TFVars
      action: fetch:template
      input:
        url: ./skeleton/terraform/environments
        targetPath: ./terraform/environments
        values:
          projectName: ${{ parameters.projectName }}
          awsRegion: ${{ parameters.awsRegion }}
          clusterVersion: ${{ parameters.clusterVersion }}
          owner: ${{ parameters.repoUrl | parseRepoUrl | pick('owner') }}
          repoName: ${{ parameters.repoUrl | parseRepoUrl | pick('repo') }}
          environments: ${{ parameters.environments }}

    # ===== PROCESSAR BLUEPRINT ADDONS =====
    - id: process-addons
      name: 🔧 Processar Blueprint Addons
      action: fetch:template
      input:
        url: ./skeleton/terraform/blueprint_addons.tf.template
        targetPath: ./terraform
        values:
          enabledAddons: ${{ parameters.enabledAddons }}

    # ===== PROCESSAR PIPELINE =====
    - id: process-pipeline
      name: ⚙️ Processar Pipeline
      action: fetch:template
      input:
        url: ./skeleton/.github
        targetPath: ./.github
        values:
          projectName: ${{ parameters.projectName }}
          environments: ${{ parameters.environments }}
          awsRegion: ${{ parameters.awsRegion }}

    # ===== REMOVER TEMPLATES PROCESSADOS =====
    - id: cleanup-templates
      name: 🧹 Limpar Templates
      action: fs:delete
      input:
        files:
          - ./terraform/blueprint_addons.tf.template
          - ./terraform/environments/dev.tfvars.template
          - ./terraform/environments/stage.tfvars.template
          - ./terraform/environments/prod.tfvars.template
          - ./.github/workflows/pipe-tofu.yaml.template

    # ===== REMOVER AMBIENTE DEV (SE NÃO SELECIONADO) =====
    - id: cleanup-dev-env
      name: 🗑️ Remover Ambiente Dev (se não selecionado)
      if: ${{ 'dev' not in parameters.environments }}
      action: fs:delete
      input:
        files:
          - ./terraform/environments/dev.tfvars

    # ===== REMOVER AMBIENTE STAGE (SE NÃO SELECIONADO) =====
    - id: cleanup-stage-env
      name: 🗑️ Remover Ambiente Stage (se não selecionado)
      if: ${{ 'stage' not in parameters.environments }}
      action: fs:delete
      input:
        files:
          - ./terraform/environments/stage.tfvars

    # ===== REMOVER AMBIENTE PROD (SE NÃO SELECIONADO) =====
    - id: cleanup-prod-env
      name: 🗑️ Remover Ambiente Prod (se não selecionado)
      if: ${{ 'prod' not in parameters.environments }}
      action: fs:delete
      input:
        files:
          - ./terraform/environments/prod.tfvars

    # ===== CRIAR PULL REQUEST =====
    - id: create-pr
      name: 📤 Criar Pull Request
      action: publish:github:pull-request
      input:
        repoUrl: ${{ parameters.repoUrl }}
        title: '🚀 feat: Adicionar infraestrutura OpenTofu para ${{ parameters.projectName }}'
        branchName: 'feat/opentofu-${{ parameters.projectName }}-${{ '' | now }}'
        description: |
          ## 🏗️ Nova Infraestrutura OpenTofu - ${{ parameters.projectName }}
          
          **Solicitado via:** Backstage Scaffolder  
          **Prioridade:** ${{ parameters.priority | upper }}  
          **Região AWS:** ${{ parameters.awsRegion }}  
          **Ambientes:** ${{ parameters.environments | join(', ') }}
          
          ### 📋 Configurações do Cluster:
          - **Versão Kubernetes:** ${{ parameters.clusterVersion }}
          - **Addons:** ${{ parameters.enabledAddons | join(', ') }}
          
          ### ✅ Checklist de Revisão:
          - [ ] Validar configurações de rede e segurança
          - [ ] Revisar addons necessários
          - [ ] Confirmar configurações de ambiente
          - [ ] Validar pipeline de CI/CD
          
          ### 🚀 Próximos Passos:
          1. **Revisar e aprovar** este PR
          2. **Executar pipeline** para aplicar a infraestrutura
          3. **Configurar aplicações** no ArgoCD (se habilitado)
          4. **Validar conectividade** e funcionalidades do cluster
          
          ### ⚠️ Importante:
          - Este PR criará recursos AWS que podem gerar custos
          - Certifique-se de que as permissões IAM estão configuradas
          
          ---
          
          **Criado em:** ${{ '' | now }}
        draft: ${{ parameters.createDraft }}
        sourcePath: .
        targetPath: .

  output:
    links:
      - title: 📋 Ver Pull Request
        url: ${{ steps['create-pr'].output.remoteUrl }}
        icon: github

      - title: 📊 Pipeline Status
        url: ${{ parameters.repoUrl | parseRepoUrl | pick('host') }}/${{ parameters.repoUrl | parseRepoUrl | pick('owner') }}/${{ parameters.repoUrl | parseRepoUrl | pick('repo') }}/actions
        icon: github

      - title: 📖 OpenTofu Documentation
        url: https://opentofu.org/docs/
        icon: docs

      - title: ☁️ AWS EKS Console
        url: https://console.aws.amazon.com/eks/home?region=${{ parameters.awsRegion }}#/clusters
        icon: cloud

    text:
      - title: 🎉 Infraestrutura OpenTofu Criada com Sucesso!
        content: |
          ## ✅ Próximos Passos:
          
          ### 1. 📋 Revisar Pull Request
          - Acesse o PR criado e revise as configurações
          - Verifique se todos os ambientes estão corretos
          
          ### 2. 🚀 Executar Pipeline
          - Após aprovação, a pipeline será executada automaticamente
          - Monitore o progresso na aba Actions do GitHub
          - A infraestrutura será criada na região **${{ parameters.awsRegion }}**
          
          ### 📊 Resumo da Configuração:
          - **Projeto:** ${{ parameters.projectName }}
          - **Ambientes:** ${{ parameters.environments | join(', ') }}
          - **Região:** ${{ parameters.awsRegion }}
          - **Kubernetes:** v${{ parameters.clusterVersion }}
          - **Addons:** ${{ parameters.enabledAddons | length }} habilitados