apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: opentofu-eks-autopilot-12
  title: OpenTofu EKS Cluster com Pipeline Autopilot -12
  description: |
    Template para criação de clusters EKS usando OpenTofu com pipeline autopilot.
    Suporta múltiplos ambientes (dev, stage, prod) com tfvars específicos.
  tags:
    - opentofu
    - terraform
    - eks
    - kubernetes
    - aws
    - gitops
    - argocd
    - infrastructure
    - autopilot

spec:
  owner: platform-team
  type: infrastructure
  
  parameters:
    # ===== CONFIGURAÇÕES PRINCIPAIS =====
    - title: 🏗️ Configurações Principais
      required:
        - projectName
        - owner
        - awsRegion
      properties:
        projectName:
          title: Nome do Repositório
          type: string
          description: Nome do repositório a ser criado
          default: meu-cluster-gitops
          pattern: '^[a-zA-Z0-9-_]+$'
        
        owner:
          title: Organização ou Usuário GitHub
          type: string
          description: Organização ou usuário GitHub que será proprietário do repositório
          default: pcnuness
          pattern: '^[a-zA-Z0-9-_]+$'

        awsRegion:
          title: Região AWS
          type: string
          description: Região AWS para deploy da infraestrutura
          default: us-east-1
          enum:
            - us-east-1
            - us-west-2
            - eu-west-1
            - eu-central-1
            - ap-southeast-1
          enumNames:
            - 'US East (N. Virginia)'
            - 'US West (Oregon)'
            - 'Europe (Ireland)'
            - 'Europe (Frankfurt)'
            - 'Asia Pacific (Singapore)'

    # ===== CONFIGURAÇÕES DE AMBIENTES =====
    - title: 🌍 Configurações de Ambientes
      properties:
        environments:
          title: Selecione os ambientes que serão configurados
          type: object
          properties:
            enabledDev:
              title: Ambiente Development
              type: boolean
              description: Habilitar ambiente de desenvolvimento
              default: true
            enabledStage:
              title: Ambiente Staging
              type: boolean
              description: Habilitar ambiente de staging
              default: false
            enabledProd:
              title: Ambiente Production
              type: boolean
              description: Habilitar ambiente de produção
              default: false

    # ===== CONFIGURAÇÕES DO CLUSTER EKS =====
    - title: ⚙️ Configurações do Cluster EKS
      required:
        - clusterVersion
      properties:
        clusterVersion:
          title: Versão do Kubernetes
          type: string
          description: Versão do Kubernetes para o cluster EKS
          default: "1.31"
          enum:
            - "1.29"
            - "1.30"
            - "1.31"
            - "1.32"

    # ===== ADDONS E COMPONENTES =====
    - title: 🔧 Addons e Componentes
      properties:
        enabledCoreDns:
          title: Addon Core DNS
          type: boolean
          description: Habilitar Core DNS
          default: true
        enabledKubeProxy:
          title: Addon Kube Proxy
          type: boolean
          description: Habilitar Kube Proxy
          default: false
        enabledPodIdentityAgent:
          title: Addon AWS Pod Identity Agent
          type: boolean
          description: Habilitar Pod Identity Agent
          default: false
        enabledEbsCsiDriver:
          title: Addon AWS EBS CSI Driver
          type: boolean
          description: Habilitar AWS EBS CSI Driver
          default: false

  steps:
    # ===== VALIDAÇÃO INICIAL =====
    - id: validate-inputs
      name: 🔍 Validar Entradas
      action: debug:log
      input:
        message: |
          Validando configurações:
          - Projeto: ${{ parameters.projectName }}
          - Owner: ${{ parameters.owner }}
          - Região: ${{ parameters.awsRegion }}
          - Cluster Version: ${{ parameters.clusterVersion }}
          - Ambientes:
              Dev: ${{ parameters.environments.enabledDev }}
              Stage: ${{ parameters.environments.enabledStage }}
              Prod: ${{ parameters.environments.enabledProd }}
          - Addons: 
              CoreDNS: ${{ parameters.enabledCoreDns }}
              KubeProxy: ${{ parameters.enabledKubeProxy }}
              PodIdentityAgent: ${{ parameters.enabledPodIdentityAgent }}
              EbsCsiDriver: ${{ parameters.enabledEbsCsiDriver }}

    # ===== CRIAR ESTRUTURA BASE =====
    - id: fetch-base-structure
      name: 📁 Criar Estrutura Base do Projeto
      action: fetch:template
      input:
        url: ./templates/terraform
        targetPath: ./terraform/
        values:
          projectName: ${{ parameters.projectName }}
          owner: ${{ parameters.owner }}
          awsRegion: ${{ parameters.awsRegion }}
          clusterVersion: ${{ parameters.clusterVersion }}
          # Ambientes
          enabledDev: ${{ parameters.environments.enabledDev }}
          enabledStage: ${{ parameters.environments.enabledStage }}
          enabledProd: ${{ parameters.environments.enabledProd }}
          # Addons
          enabledCoreDns: ${{ parameters.enabledCoreDns }}
          enabledKubeProxy: ${{ parameters.enabledKubeProxy }}
          enabledPodIdentityAgent: ${{ parameters.enabledPodIdentityAgent }}
          enabledEbsCsiDriver: ${{ parameters.enabledEbsCsiDriver }}

    # ===== CRIAR CONFIGURAÇÕES POR AMBIENTE =====
    - id: create-environment-prod
      name: 🌍 Criar Configurações por Ambiente
      action: fetch:template
      if: ${{ parameters.environments.enabledProd }}
      input:
        url: ./skeleton/environments/prod.tfvars
        targetPath: ./terraform/environments/prod.tfvars
        values:
          projectName: ${{ parameters.projectName }}
          awsRegion: ${{ parameters.awsRegion }}
          clusterVersion: ${{ parameters.clusterVersion }}
          enabledProd: ${{ parameters.environments.enabledProd }}
    
    # ===== CRIAR CONFIGURAÇÕES POR AMBIENTE =====
    - id: create-environment-stage
      name: 🌍 Criar Configurações por Ambiente
      action: fetch:template
      if: ${{ parameters.environments.enabledStage }}
      input:
        url: ./skeleton/environments/stage.tfvars
        targetPath: ./terraform/environments/stage.tfvars
        values:
          projectName: ${{ parameters.projectName }}
          awsRegion: ${{ parameters.awsRegion }}
          clusterVersion: ${{ parameters.clusterVersion }}
          enabledStage: ${{ parameters.environments.enabledStage }}
    
    # ===== CRIAR CONFIGURAÇÕES POR AMBIENTE =====
    - id: create-environment-configs
      name: 🌍 Criar Configurações por Ambiente
      action: fetch:template
      if: ${{ parameters.environments.enabledDev }}
      input:
        url: ./skeleton/environments/dev.tfvars
        targetPath: ./terraform/environments/dev.tfvars
        values:
          projectName: ${{ parameters.projectName }}
          awsRegion: ${{ parameters.awsRegion }}
          clusterVersion: ${{ parameters.clusterVersion }}
          enabledDev: ${{ parameters.environments.enabledDev }}

    # ===== CRIAR REPOSITÓRIO =====
    - id: publish-repo
      name: 📦 Criar Repositório
      action: publish:github
      input:
        repoUrl: "github.com?owner=${{ parameters.owner }}&repo=${{ parameters.projectName }}"
        description: 'Infraestrutura EKS para ${{ parameters.projectName }} usando OpenTofu'
        topics:
          - opentofu
          - terraform
          - eks
          - kubernetes
          - aws
          - infrastructure
          - ${{ parameters.projectName }}
        defaultBranch: main
        gitAuthorName: Backstage Scaffolder
        gitAuthorEmail: scaffolder@backstage.io
        repoVisibility: public
        gitCommitMessage: |
          🚀 Initial commit: OpenTofu EKS Infrastructure for ${{ parameters.projectName }}
          
          - Configuração completa de cluster EKS
          - Pipeline autopilot com GitHub Actions
          - Suporte a múltiplos ambientes
          - Região: ${{ parameters.awsRegion }}
          - Kubernetes: v${{ parameters.clusterVersion }}
          
          Criado via Backstage Scaffolder

    # ===== REGISTRAR NO CATÁLOGO =====
    - id: register-catalog
      name: 📋 Registrar no Catálogo
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish-repo'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'
        optional: true

  output:
    links:
      - title: 📦 Ver Repositório
        url: ${{ steps['publish-repo'].output.remoteUrl }}
        icon: github

      - title: 📊 Pipeline Status
        url: ${{ steps['publish-repo'].output.remoteUrl }}/actions
        icon: github

    text:
      - title: 🎉 Infraestrutura OpenTofu Criada com Sucesso!
        content: |
          ## ✅ Repositório Criado:
          
          **Repositório:** ${{ steps['publish-repo'].output.remoteUrl }}
          
          ## 📊 Resumo da Configuração:
          - **Projeto:** ${{ parameters.projectName }}
          - **Região:** ${{ parameters.awsRegion }}
          - **Kubernetes:** v${{ parameters.clusterVersion }}
          - **Ambientes Habilitados:**
            - Development: ${{ parameters.environments.enabledDev }}
            - Staging: ${{ parameters.environments.enabledStage }}
            - Production: ${{ parameters.environments.enabledProd }}
          - **Addons Habilitados:**
            - CoreDNS: ${{ parameters.enabledCoreDns }}
            - Kube-Proxy: ${{ parameters.enabledKubeProxy }}
            - Pod Identity Agent: ${{ parameters.enabledPodIdentityAgent }}
            - EBS CSI Driver: ${{ parameters.enabledEbsCsiDriver }}