apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: provisionar-addons-gitops
  title: Criar estrutura GitOps com Add-ons
  description: Criação de estrutura GitOps com escolha de Add-ons
spec:
  owner: gitops-plataform
  type: service

  parameters:
    - title: Parâmetros da estrutura
      required: [projectName, owner]
      properties:
        projectName:
          title: Nome do Repositório
          type: string
          default: gitops-cluster
        owner:
          title: Organização ou Usuário GitHub
          type: string
          default: pcnuness
    - title: Selecione Addons
      type: object
      properties:
        aws-alb-controller:
          type: boolean
          title: Incluir AWS-Load-Balancer-Controller
          default: true
        ingressNginx:
          type: boolean
          title: Incluir Ingress-Nginx
          default: true
        keda:
          type: boolean
          title: Incluir KEDA
          default: false

  steps:
    #- id: fetch-template
    #  name: Gerar estrutura GitOps com Addons
    #  action: fetch:template
    #  input:
    #    targetPath: "."
    #    url: "./templates"
    #    values:
    #      projectName: ${{ parameters.projectName }}
    #      owner: ${{ parameters.owner }}
    #      addons: ${{ parameters.addons }}
    - id: fetch-base
      name: Buscar estrutura base
      action: fetch:template
      input:
        url: ./templates/cluster-management
        targetPath: .
        values:
          projectName: ${{ parameters.projectName }}
          owner: ${{ parameters.owner }}

    - id: copiar-addons
      name: Copiar arquivos dos add-ons selecionados
      action: fs:copy
      input:
        files:
          {% if parameters.aws-alb-controller %}
          - from: ./templates/addons/aws/appset-load-balancer-controller.yaml
            to: ./cluster-management/bootstraps/crontrol-plane/addons/aws/
          {% endif %}
          {% if parameters.ingressNginx %}
          - from: ./templates/addons/oss/appset-ingress-nginx.yaml
            to: ./cluster-management/bootstraps/crontrol-plane/addons/oss/
          {% endif %}

    - id: push-initial
      name: Push Inicial
      action: publish:github
      input:
        repoUrl: "github.com?owner=${{ parameters.owner }}&repo=${{ parameters.projectName }}"
        branch: main
        defaultBranch: main
        repoVisibility: public
        committerName: "Backstage Scaffolder"
        committerEmail: "scaffolder@mydomain.com"
        authorName: "Backstage Scaffolder"
        authorEmail: "scaffolder@mydomain.com"
        commitMessage: "Initial commit from Scaffolder"
        files:
          - source: "."
            target: "/"

  output:
    links:
      - title: Repositório GitHub
        url: "https://github.com/${{ parameters.owner }}/${{ parameters.projectName }}"