apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: provisionar-addons-gitops
  title: Criar estrutura GitOps com Add-ons
  description: Criação de estrutura GitOps com escolha de Add-ons
spec:
  owner: gitops-plataform
  type: service

  parameters:
    - title: Parâmetros da estrutura
      required: [projectName, owner]
      properties:
        projectName:
          title: Nome do Repositório
          type: string
          default: gitops-cluster
        owner:
          title: Organização ou Usuário GitHub
          type: string
          default: pcnuness
        addons:
          title: Add-ons a incluir
          type: array
          items:
            type: string
            enum:
              - aws-load-balancer-controller
              - ingress-nginx
          uniqueItems: true
          description: Selecione os add-ons desejados

  steps:
    - id: fetch-base
      name: Buscar Template Base
      action: fetch:template
      input:
        url: ./template
        values:
          projectName: ${{ parameters.projectName }}
          addons: ${{ parameters.addons }}
    
    - id: publish
      name: Publicar no Repositório
      action: publish:github
      input:
        repoUrl: https://github.com/${{ parameters.owner }}/${{ parameters.projectName }}"
        repoVisibility: public