apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: adicionar-addons-gitops
  title: Adicionar Addons GitOps
  description: Adiciona addons em repositório GitOps existente via Pull Request
  tags:
    - kubernetes
    - gitops
    - addons
    - pull-request
spec:
  owner: plataforma-gitops
  type: service
  parameters:
    - title: Configurações do Repositório
      required:
        - repositoryPicker
      properties:
        repositoryPicker:
          title: Selecionar Repositório GitOps
          type: string
          description: Selecione o repositório GitOps existente
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
            allowedOwners:
              - pcnuness
              - sua-org
              - outra-org
        targetBranch:
          title: Branch Base
          type: string
          description: Branch base para criar o PR
          default: main
        prTitle:
          title: Título do Pull Request
          type: string
          description: Título personalizado para o PR
          default: "feat: Adicionar addons GitOps via Backstage"

    - title: Seleção de Addons AWS
      properties:
        enableAwsAlbController:
          title: AWS Load Balancer Controller
          type: boolean
          description: AWS Application Load Balancer Controller
          default: false
        
    - title: Seleção de Addons OSS
      properties:
        enableIngressNginx:
          title: Ingress NGINX
          type: boolean
          description: Ingress NGINX Controller
          default: false
        enableArgoCdIngress:
          title: ArgoCD Ingress
          type: boolean
          description: Configuração de Ingress para ArgoCD
          default: false
        enableCrossplane:
          title: Crossplane
          type: boolean
          description: Crossplane para gerenciamento de infraestrutura
          default: false
        enableKarpenter:
          title: Karpenter
          type: boolean
          description: Karpenter para autoscaling de Nodes
          default: false
        enableKubePrometheusStack:
          title: Kube Prometheus Stack
          type: boolean
          description: Stack de monitoramento Prometheus
          default: false
        enableMetricsServer:
          title: Metrics Server
          type: boolean
          description: Metrics Server para monitoramento
          default: false

    - title: Configurações de Aprovação
      properties:
        requiresApproval:
          title: Requer Aprovação
          type: boolean
          description: PR requer aprovação antes do merge
          default: true
        reviewers:
          title: Revisores
          type: array
          description: Lista de usuários/equipes para revisar o PR
          items:
            type: string
          default: ["@plataforma-gitops", "@devops-team"]
        priority:
          title: Prioridade
          type: string
          description: Prioridade da mudança
          enum:
            - low
            - medium
            - high
            - critical
          enumNames:
            - Baixa
            - Média
            - Alta
            - Crítica
          default: medium
        createDraft:
          title: Criar como Draft
          type: boolean
          description: Criar PR como draft (exceto para prioridade crítica)
          default: true

  steps:
    - id: fetch-repository
      name: Clonar Repositório Existente
      action: fetch:plain
      input:
        url: ${{ parameters.repositoryPicker | parseRepoUrl | pick('repo') }}
        targetPath: ./repo

    # STEPS PARA ADICIONAR ADDONS
    - id: fetch-aws-alb-controller
      name: Adicionar AWS Load Balancer Controller
      if: ${{ parameters.enableAwsAlbController }}
      action: fetch:template
      input:
        url: ./templates/addons-operations/aws/aws-load-balancer-controller/
        targetPath: ./repo/bootstraps/control-plane/addons/aws/
        values:
          projectName: ${{ parameters.repositoryPicker | parseRepoUrl | pick('repo') }}
          repoOwner: ${{ parameters.repositoryPicker | parseRepoUrl | pick('owner') }}

    - id: fetch-ingress-nginx
      name: Adicionar Ingress NGINX
      if: ${{ parameters.enableIngressNginx }}
      action: fetch:template
      input:
        url: ./templates/addons-operations/oss/ingress-nginx/
        targetPath: ./repo/bootstraps/control-plane/addons/oss/
        values:
          projectName: ${{ parameters.repositoryPicker | parseRepoUrl | pick('repo') }}
          repoOwner: ${{ parameters.repositoryPicker | parseRepoUrl | pick('owner') }}

    - id: fetch-argocd-ingress
      name: Adicionar ArgoCD Ingress
      if: ${{ parameters.enableArgoCdIngress }}
      action: fetch:template
      input:
        url: ./templates/addons-operations/oss/argocd-ingress/
        targetPath: ./repo/bootstraps/control-plane/addons/oss/
        values:
          projectName: ${{ parameters.repositoryPicker | parseRepoUrl | pick('repo') }}
          repoOwner: ${{ parameters.repositoryPicker | parseRepoUrl | pick('owner') }}

    - id: fetch-crossplane
      name: Adicionar Crossplane
      if: ${{ parameters.enableCrossplane }}
      action: fetch:template
      input:
        url: ./templates/addons-operations/oss/crossplane/
        targetPath: ./repo/bootstraps/control-plane/addons/oss/
        values:
          projectName: ${{ parameters.repositoryPicker | parseRepoUrl | pick('repo') }}
          repoOwner: ${{ parameters.repositoryPicker | parseRepoUrl | pick('owner') }}

    - id: fetch-karpenter
      name: Adicionar Karpenter
      if: ${{ parameters.enableKarpenter }}
      action: fetch:template
      input:
        url: ./templates/addons-operations/oss/karpenter/
        targetPath: ./repo/bootstraps/control-plane/addons/oss/
        values:
          projectName: ${{ parameters.repositoryPicker | parseRepoUrl | pick('repo') }}
          repoOwner: ${{ parameters.repositoryPicker | parseRepoUrl | pick('owner') }}

    - id: fetch-kube-prometheus-stack
      name: Adicionar Kube Prometheus Stack
      if: ${{ parameters.enableKubePrometheusStack }}
      action: fetch:template
      input:
        url: ./templates/addons-operations/oss/kube-prometheus-stack/
        targetPath: ./repo/bootstraps/control-plane/addons/oss/
        values:
          projectName: ${{ parameters.repositoryPicker | parseRepoUrl | pick('repo') }}
          repoOwner: ${{ parameters.repositoryPicker | parseRepoUrl | pick('owner') }}

    - id: fetch-metrics-server
      name: Adicionar Metrics Server
      if: ${{ parameters.enableMetricsServer }}
      action: fetch:template
      input:
        url: ./templates/addons-operations/oss/metrics-server/
        targetPath: ./repo/bootstraps/control-plane/addons/oss/
        values:
          projectName: ${{ parameters.repositoryPicker | parseRepoUrl | pick('repo') }}
          repoOwner: ${{ parameters.repositoryPicker | parseRepoUrl | pick('owner') }}

    # PUBLICAR PR PARA PRIORIDADE CRÍTICA
    - id: publish-pr-critical
      name: Criar Pull Request (Prioridade Crítica)
      if: ${{ parameters.priority === 'critical' }}
      action: publish:github:pull-request
      input:
        repoUrl: ${{ parameters.repositoryPicker }}
        title: ${{ parameters.prTitle }}
        branchName: feature/addons-add-critical
        description: |
          ## 🚨 ADIÇÃO CRÍTICA - Addons GitOps

          **Operação:** Adição de addons
          **Prioridade:** CRÍTICA 🚨
          **Solicitado via:** Backstage Scaffolder
          **Repositório:** ${{ parameters.repositoryPicker | parseRepoUrl | pick('owner') }}/${{ parameters.repositoryPicker | parseRepoUrl | pick('repo') }}

          ### 📦 Addons Adicionados:
          ${{ parameters.enableAwsAlbController ? '- ✅ AWS Load Balancer Controller' : '' }}
          ${{ parameters.enableIngressNginx ? '- ✅ Ingress NGINX' : '' }}
          ${{ parameters.enableArgoCdIngress ? '- ✅ ArgoCD Ingress' : '' }}
          ${{ parameters.enableCrossplane ? '- ✅ Crossplane' : '' }}
          ${{ parameters.enableKarpenter ? '- ✅ Karpenter' : '' }}
          ${{ parameters.enableKubePrometheusStack ? '- ✅ Kube Prometheus Stack' : '' }}
          ${{ parameters.enableMetricsServer ? '- ✅ Metrics Server' : '' }}

          ### ⚠️ ATENÇÃO - PRIORIDADE CRÍTICA:
          - Este PR requer aprovação imediata
          - Mudanças serão aplicadas automaticamente pelo ArgoCD após o merge
          - Monitorar cluster após aplicação

          ### 🔍 Checklist de Revisão:
          - [ ] Validar sintaxe YAML dos arquivos
          - [ ] Verificar compatibilidade com cluster existente
          - [ ] Confirmar configurações de recursos (CPU/Memory)
          - [ ] Validar dependências entre addons

          ### 🚀 Próximos Passos:
          1. Aprovação imediata pelos revisores
          2. Merge automático após aprovação
          3. Monitoramento da sincronização ArgoCD
          4. Validação da saúde dos addons

        targetBranch: ${{ parameters.targetBranch }}
        sourcePath: ./repo
        reviewers: ${{ parameters.reviewers }}
        draft: false

    # PUBLICAR PR PARA OUTRAS PRIORIDADES
    - id: publish-pr-normal
      name: Criar Pull Request (Prioridade Normal)
      if: ${{ parameters.priority !== 'critical' }}
      action: publish:github:pull-request
      input:
        repoUrl: ${{ parameters.repositoryPicker }}
        title: ${{ parameters.prTitle }}
        branchName: feature/addons-add-${{ parameters.priority }}
        description: |
          ## ✅ Adição de Addons GitOps

          **Operação:** Adição de addons
          **Prioridade:** ${{ parameters.priority }}
          **Solicitado via:** Backstage Scaffolder
          **Repositório:** ${{ parameters.repositoryPicker | parseRepoUrl | pick('owner') }}/${{ parameters.repositoryPicker | parseRepoUrl | pick('repo') }}

          ### 📦 Addons Adicionados:
          {% if parameters.enableAwsAlbController %}
          - ✅ AWS Load Balancer Controller
          {% endif %}
          {% if parameters.enableIngressNginx %}
          - ✅ Ingress NGINX
          {% endif %}
          {% if parameters.enableArgoCdIngress %}
          - ✅ ArgoCD Ingress
          {% endif %}
          {% if parameters.enableCrossplane %}
          - ✅ Crossplane
          {% endif %}
          {% if parameters.enableKarpenter %}
          - ✅ Karpenter
          {% endif %}
          {% if parameters.enableKubePrometheusStack %}
          - ✅ Kube Prometheus Stack
          {% endif %}
          {% if parameters.enableMetricsServer %}
          - ✅ Metrics Server
          {% endif %}

          ### 🔍 Checklist de Revisão:
          - [ ] Validar sintaxe YAML dos arquivos
          - [ ] Verificar compatibilidade com cluster existente
          - [ ] Confirmar configurações de recursos (CPU/Memory)
          - [ ] Validar dependências entre addons
          - [ ] Testar em ambiente de desenvolvimento (se aplicável)

          ### 🚀 Próximos Passos Pós-Merge:
          1. ArgoCD detectará automaticamente as mudanças
          2. Monitorar logs de sincronização no ArgoCD
          3. Validar saúde dos addons no cluster
          4. Executar testes de conectividade (se aplicável)

          ### 🔄 Rollback:
          Em caso de problemas, reverter este PR ou aplicar:
          ```bash
          kubectl delete -f <arquivo-addon-problemático>
          ```

          ### 📋 Informações Técnicas:
          - **Repositório:** ${{ parameters.repositoryPicker | parseRepoUrl | pick('owner') }}/${{ parameters.repositoryPicker | parseRepoUrl | pick('repo') }}
          - **Branch Base:** ${{ parameters.targetBranch }}
          - **Revisores:** ${{ parameters.reviewers | join(', ') }}

        targetBranch: ${{ parameters.targetBranch }}
        sourcePath: ./repo
        reviewers: ${{ parameters.reviewers }}
        draft: ${{ parameters.createDraft }}

  output:
    links:
      - title: Ver Pull Request (Crítico)
        if: ${{ parameters.priority === 'critical' }}
        url: ${{ steps['publish-pr-critical'].output.remoteUrl }}
        icon: github
      - title: Ver Pull Request (Normal)
        if: ${{ parameters.priority !== 'critical' }}
        url: ${{ steps['publish-pr-normal'].output.remoteUrl }}
        icon: github
    text:
      - title: Pull Request Criado
        content: |
          ## 🎉 Pull Request de Adição Criado com Sucesso!

          **Repositório:** ${{ parameters.repositoryPicker | parseRepoUrl | pick('owner') }}/${{ parameters.repositoryPicker | parseRepoUrl | pick('repo') }}
          **Prioridade:** ${{ parameters.priority }}
          **Operação:** Adição de addons

          ### 📋 Próximos Passos:
          1. **Revisão:** Aguardar aprovação dos revisores designados
          2. **Testes:** Executar validações automáticas
          3. **Merge:** Após aprovação, realizar merge
          4. **Monitoramento:** Acompanhar sincronização no ArgoCD

          ### 🔧 Addons Adicionados:
          {% if parameters.enableAwsAlbController %}
          - ✅ AWS Load Balancer Controller
          {% endif %}
          {% if parameters.enableIngressNginx %}
          - ✅ Ingress NGINX
          {% endif %}
          {% if parameters.enableArgoCdIngress %}
          - ✅ ArgoCD Ingress
          {% endif %}
          {% if parameters.enableCrossplane %}
          - ✅ Crossplane
          {% endif %}
          {% if parameters.enableKarpenter %}
          - ✅ Karpenter
          {% endif %}
          {% if parameters.enableKubePrometheusStack %}
          - ✅ Kube Prometheus Stack
          {% endif %}
          {% if parameters.enableMetricsServer %}
          - ✅ Metrics Server
          {% endif %}

          ### ⚠️ Importante:
          - Este PR adiciona novos addons ao cluster
          - Mudanças serão aplicadas automaticamente pelo ArgoCD após o merge
          - Em caso de problemas, utilize o processo de rollback documentado

          ### 🔗 Links Úteis:
          - [Documentação ArgoCD](https://argo-cd.readthedocs.io/)
          - [Guia de Troubleshooting](https://your-docs.com/troubleshooting)
          - [Processo de Rollback](https://your-docs.com/rollback)