apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: gerenciar-addons-gitops
  title: Gerenciar Addons GitOps - Adicionar/Remover
  description: Adiciona ou remove addons em repositório GitOps existente via Pull Request
  tags:
    - kubernetes
    - gitops
    - addons
    - pull-request
spec:
  owner: plataforma-gitops
  type: service
  parameters:
    - title: Configurações do Repositório
      required:
        - repositoryPicker
        - operation
      properties:
        repositoryPicker:
          title: Selecionar Repositório GitOps
          type: string
          description: Selecione o repositório GitOps existente
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
            allowedOwners:
              - pcnuness
              - sua-org
              - outra-org
        operation:
          title: Operação
          type: string
          description: Tipo de operação a ser realizada
          enum:
            - add
            - remove
          enumNames:
            - Adicionar Addons
            - Remover Addons
        targetBranch:
          title: Branch Base
          type: string
          description: Branch base para criar o PR
          default: main
        prTitle:
          title: Título do Pull Request
          type: string
          description: Título personalizado para o PR
          default: "feat: Atualização de addons GitOps via Backstage"

    - title: Seleção de Addons AWS
      properties:
        enableAwsAlbController:
          title: AWS Load Balancer Controller
          type: boolean
          description: AWS Application Load Balancer Controller
          default: false
        
    - title: Seleção de Addons OSS
      properties:
        enableIngressNginx:
          title: Ingress NGINX
          type: boolean
          description: Ingress NGINX Controller
          default: false
        enableArgoCdIngress:
          title: ArgoCD Ingress
          type: boolean
          description: Configuração de Ingress para ArgoCD
          default: false
        enableCrossplane:
          title: Crossplane
          type: boolean
          description: Crossplane para gerenciamento de infraestrutura
          default: false
        enableKarpenter:
          title: Karpenter
          type: boolean
          description: Karpenter para autoscaling de Nodes
          default: false
        enableKubePrometheusStack:
          title: Kube Prometheus Stack
          type: boolean
          description: Stack de monitoramento Prometheus
          default: false
        enableMetricsServer:
          title: Metrics Server
          type: boolean
          description: Metrics Server para monitoramento
          default: false

    - title: Configurações de Aprovação
      properties:
        requiresApproval:
          title: Requer Aprovação
          type: boolean
          description: PR requer aprovação antes do merge
          default: true
        reviewers:
          title: Revisores
          type: array
          description: Lista de usuários/equipes para revisar o PR
          items:
            type: string
          default: ["@plataforma-gitops", "@devops-team"]
        priority:
          title: Prioridade
          type: string
          description: Prioridade da mudança
          enum:
            - low
            - medium
            - high
            - critical
          enumNames:
            - Baixa
            - Média
            - Alta
            - Crítica
          default: medium
        createDraft:
          title: Criar como Draft
          type: boolean
          description: Criar PR como draft (exceto para prioridade crítica)
          default: true

  steps:
    - id: fetch-repository
      name: Clonar Repositório Existente
      action: fetch:plain
      input:
        url: ${{ parameters.repositoryPicker | parseRepoUrl | pick('repo') }}
        targetPath: ./repo

    # STEPS PARA ADICIONAR ADDONS (mantém igual ao anterior)
    - id: fetch-aws-alb-controller
      name: Adicionar AWS Load Balancer Controller
      if: ${{ parameters.operation === 'add' and parameters.enableAwsAlbController }}
      action: fetch:template
      input:
        url: ./templates/addons-operations/aws/aws-load-balancer-controller/
        targetPath: ./repo/bootstraps/control-plane/addons/aws/
        values:
          projectName: ${{ parameters.repositoryPicker | parseRepoUrl | pick('repo') }}
          repoOwner: ${{ parameters.repositoryPicker | parseRepoUrl | pick('owner') }}

    - id: fetch-ingress-nginx
      name: Adicionar Ingress NGINX
      if: ${{ parameters.operation === 'add' and parameters.enableIngressNginx }}
      action: fetch:template
      input:
        url: ./templates/addons-operations/oss/ingress-nginx/
        targetPath: ./repo/bootstraps/control-plane/addons/oss/
        values:
          projectName: ${{ parameters.repositoryPicker | parseRepoUrl | pick('repo') }}
          repoOwner: ${{ parameters.repositoryPicker | parseRepoUrl | pick('owner') }}

    - id: fetch-argocd-ingress
      name: Adicionar ArgoCD Ingress
      if: ${{ parameters.operation === 'add' and parameters.enableArgoCdIngress }}
      action: fetch:template
      input:
        url: ./templates/addons-operations/oss/argocd-ingress/
        targetPath: ./repo/bootstraps/control-plane/addons/oss/
        values:
          projectName: ${{ parameters.repositoryPicker | parseRepoUrl | pick('repo') }}
          repoOwner: ${{ parameters.repositoryPicker | parseRepoUrl | pick('owner') }}

    - id: fetch-crossplane
      name: Adicionar Crossplane
      if: ${{ parameters.operation === 'add' and parameters.enableCrossplane }}
      action: fetch:template
      input:
        url: ./templates/addons-operations/oss/crossplane/
        targetPath: ./repo/bootstraps/control-plane/addons/oss/
        values:
          projectName: ${{ parameters.repositoryPicker | parseRepoUrl | pick('repo') }}
          repoOwner: ${{ parameters.repositoryPicker | parseRepoUrl | pick('owner') }}

    - id: fetch-karpenter
      name: Adicionar Karpenter
      if: ${{ parameters.operation === 'add' and parameters.enableKarpenter }}
      action: fetch:template
      input:
        url: ./templates/addons-operations/oss/karpenter/
        targetPath: ./repo/bootstraps/control-plane/addons/oss/
        values:
          projectName: ${{ parameters.repositoryPicker | parseRepoUrl | pick('repo') }}
          repoOwner: ${{ parameters.repositoryPicker | parseRepoUrl | pick('owner') }}

    - id: fetch-kube-prometheus-stack
      name: Adicionar Kube Prometheus Stack
      if: ${{ parameters.operation === 'add' and parameters.enableKubePrometheusStack }}
      action: fetch:template
      input:
        url: ./templates/addons-operations/oss/kube-prometheus-stack/
        targetPath: ./repo/bootstraps/control-plane/addons/oss/
        values:
          projectName: ${{ parameters.repositoryPicker | parseRepoUrl | pick('repo') }}
          repoOwner: ${{ parameters.repositoryPicker | parseRepoUrl | pick('owner') }}

    - id: fetch-metrics-server
      name: Adicionar Metrics Server
      if: ${{ parameters.operation === 'add' and parameters.enableMetricsServer }}
      action: fetch:template
      input:
        url: ./templates/addons-operations/oss/metrics-server/
        targetPath: ./repo/bootstraps/control-plane/addons/oss/
        values:
          projectName: ${{ parameters.repositoryPicker | parseRepoUrl | pick('repo') }}
          repoOwner: ${{ parameters.repositoryPicker | parseRepoUrl | pick('owner') }}

    # STEPS PARA REMOVER ADDONS (mantém igual ao anterior)
    - id: remove-aws-alb-controller
      name: Remover AWS Load Balancer Controller
      if: ${{ parameters.operation === 'remove' and parameters.enableAwsAlbController }}
      action: fs:delete
      input:
        files:
          - ./repo/bootstraps/control-plane/addons/aws/appset-load-balancer-controller.yaml

    - id: remove-ingress-nginx
      name: Remover Ingress NGINX
      if: ${{ parameters.operation === 'remove' and parameters.enableIngressNginx }}
      action: fs:delete
      input:
        files:
          - ./repo/bootstraps/control-plane/addons/oss/appset-ingress-nginx.yaml

    - id: remove-argocd-ingress
      name: Remover ArgoCD Ingress
      if: ${{ parameters.operation === 'remove' and parameters.enableArgoCdIngress }}
      action: fs:delete
      input:
        files:
          - ./repo/bootstraps/control-plane/addons/oss/appset-argocd-ingress.yaml

    - id: remove-crossplane
      name: Remover Crossplane
      if: ${{ parameters.operation === 'remove' and parameters.enableCrossplane }}
      action: fs:delete
      input:
        files:
          - ./repo/bootstraps/control-plane/addons/oss/appset-crossplane.yaml
          - ./repo/bootstraps/control-plane/addons/oss/appset-crossplane-aws-upbound.yaml

    - id: remove-karpenter
      name: Remover Karpenter
      if: ${{ parameters.operation === 'remove' and parameters.enableKarpenter }}
      action: fs:delete
      input:
        files:
          - ./repo/bootstraps/control-plane/addons/oss/appset-karpenter.yaml

    - id: remove-kube-prometheus-stack
      name: Remover Kube Prometheus Stack
      if: ${{ parameters.operation === 'remove' and parameters.enableKubePrometheusStack }}
      action: fs:delete
      input:
        files:
          - ./repo/bootstraps/control-plane/addons/oss/appset-kube-prometheus-stack.yaml

    - id: remove-metrics-server
      name: Remover Metrics Server
      if: ${{ parameters.operation === 'remove' and parameters.enableMetricsServer }}
      action: fs:delete
      input:
        files:
          - ./repo/bootstraps/control-plane/addons/oss/appset-metrics-server.yaml

    # CRIAR TEMPLATE DE DESCRIÇÃO DO PR
    - id: create-pr-description
      name: Gerar Descrição do PR
      action: fetch:template
      input:
        url: ./templates/pr-description-template/
        targetPath: ./temp-pr-description/
        values:
          operation: ${{ parameters.operation }}
          operationText: ${{ parameters.operation === 'add' ? 'Adição' : 'Remoção' }}
          priority: ${{ parameters.priority }}
          repoOwner: ${{ parameters.repositoryPicker | parseRepoUrl | pick('owner') }}
          repoName: ${{ parameters.repositoryPicker | parseRepoUrl | pick('repo') }}
          targetBranch: ${{ parameters.targetBranch }}
          enableAwsAlbController: ${{ parameters.enableAwsAlbController }}
          enableIngressNginx: ${{ parameters.enableIngressNginx }}
          enableArgoCdIngress: ${{ parameters.enableArgoCdIngress }}
          enableCrossplane: ${{ parameters.enableCrossplane }}
          enableKarpenter: ${{ parameters.enableKarpenter }}
          enableKubePrometheusStack: ${{ parameters.enableKubePrometheusStack }}
          enableMetricsServer: ${{ parameters.enableMetricsServer }}
          reviewersList: ${{ parameters.reviewers | join(', ') }}

    # PUBLICAR PR PARA PRIORIDADE CRÍTICA
    - id: publish-pr-critical
      name: Criar Pull Request (Prioridade Crítica)
      if: ${{ parameters.priority === 'critical' }}
      action: publish:github:pull-request
      input:
        repoUrl: ${{ parameters.repositoryPicker }}
        title: ${{ parameters.prTitle }}
        branchName: feature/addons-update-critical
        description: ${{ steps['create-pr-description'].output.content }}
        targetBranch: ${{ parameters.targetBranch }}
        sourcePath: ./repo
        reviewers: ${{ parameters.reviewers }}
        draft: false

    # PUBLICAR PR PARA OUTRAS PRIORIDADES
    - id: publish-pr-normal
      name: Criar Pull Request (Prioridade Normal)
      if: ${{ parameters.priority !== 'critical' }}
      action: publish:github:pull-request
      input:
        repoUrl: ${{ parameters.repositoryPicker }}
        title: ${{ parameters.prTitle }}
        branchName: feature/addons-update-${{ parameters.operation }}-${{ parameters.priority }}
        description: ${{ steps['create-pr-description'].output.content }}
        targetBranch: ${{ parameters.targetBranch }}
        sourcePath: ./repo
        reviewers: ${{ parameters.reviewers }}
        draft: ${{ parameters.createDraft }}

  output:
    links:
      - title: Ver Pull Request (Crítico)
        if: ${{ parameters.priority === 'critical' }}
        url: ${{ steps['publish-pr-critical'].output.remoteUrl }}
        icon: github
      - title: Ver Pull Request (Normal)
        if: ${{ parameters.priority !== 'critical' }}
        url: ${{ steps['publish-pr-normal'].output.remoteUrl }}
        icon: github
    text:
      - title: Pull Request Criado
        content: |
          ## 🎉 Pull Request Criado com Sucesso!

          **Repositório:** ${{ parameters.repositoryPicker | parseRepoUrl | pick('owner') }}/${{ parameters.repositoryPicker | parseRepoUrl | pick('repo') }}
          **Prioridade:** ${{ parameters.priority }}
          **Operação:** ${{ parameters.operation === 'add' ? 'Adição' : 'Remoção' }} de addons

          ### 📋 Próximos Passos:
          1. **Revisão:** Aguardar aprovação dos revisores designados
          2. **Testes:** Executar validações automáticas
          3. **Merge:** Após aprovação, realizar merge
          4. **Monitoramento:** Acompanhar sincronização no ArgoCD

          ### 🔧 Addons Processados:
          ${{ parameters.enableAwsAlbController ? '- AWS Load Balancer Controller' : '' }}
          ${{ parameters.enableIngressNginx ? '- Ingress NGINX' : '' }}
          ${{ parameters.enableArgoCdIngress ? '- ArgoCD Ingress' : '' }}
          ${{ parameters.enableCrossplane ? '- Crossplane' : '' }}
          ${{ parameters.enableKarpenter ? '- Karpenter' : '' }}
          ${{ parameters.enableKubePrometheusStack ? '- Kube Prometheus Stack' : '' }}
          ${{ parameters.enableMetricsServer ? '- Metrics Server' : '' }}