AWSTemplateFormatVersion: '2010-09-09'
Description: "Provisionamento de CloudFront com S3"
Parameters:
  BucketName:
    Type: String
    Default: ${{ bucketName | dump}}
    Description: "Nome do Bucket S3"
  AcmCertificateArn:
    Type: String
    Default: ${{ acmCertificateArn | dump}}
    Description: "ARN do Certificado SSL no ACM"
  CloudFrontAlias:
    Type: String
    Default: ${{ cloudFrontAlias | dump}}
    Description: "Domínio configurado para o CloudFront"
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt S3Bucket.DomainName
            S3OriginConfig:
              OriginAccessIdentity: origin-access-identity/cloudfront/E27O3C5B2L8I0G
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
        ViewerCertificate:
          AcmCertificateArn: !Ref AcmCertificateArn
          SslSupportMethod: sni-only
        Aliases:
          - !Ref CloudFrontAlias
Outputs:
  CloudFrontDistributionId:
    Value: !Ref CloudFrontDistribution
    Description: "ID da distribuição CloudFront provisionada"